# Query my default IP address only on startup
[wifi]
command=./get_ip_essid.sh
interval=60
separator=true
#color=#91E78B

[vpn]
command=./get_vpn.sh
interval=15
separator=true
#color=#91E78B

[cpu]
command=echo 🌡️$(awk '{print $1 / 1000}' /sys/class/thermal/thermal_zone0/temp)° C
interval=10
separator=false

[cpu2]
full_text= 
command=alacritty -e glances
separator=true

[ramusage]
command=echo 🧠 $(free -m | awk 'FNR == 2{printf("Mem %.1f% ", $3 / $2 * 100)} FNR == 3     {printf("Swap %.1f%\n", $3 / $2 * 100)}') 
interval=10
separator=true

#color=#4ec511

#main disk
[/storage]
command= echo 💾 / $(df -h / | tail -n 1 | sed 's/..................................//;s/..$//')
interval=60
separator=true

[/homestorage]
command=echo 🏠 /home $(df -h /home | tail -n 1 | sed 's/..................................//;s/......$//')
interval=60
separator=true

[packages]
command=echo 📦 $(pacman -Q | wc -l)
interval=900

[volume]
command=./volume_print.sh
interval=1
separator=true

[brightness]
command=./get_brightness.sh
interval=1

[battery]
command=./get_battery.sh
interval=15
separator=true

#date
[date]
command=echo 📆 $(date '+%a %m/%d %I:%M %p')
interval=60


#scan
[scan]
full_text=🖨️
command=~/Scripts/brother_scan.sh
